"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2025-11-26 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    columns = [c['name'] for c in insp.get_columns('queue_items')]
    
    # Cleanup leftover temp table from failed batch migrations
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_queue_items')
    
    if 'debug' not in columns:
        with op.batch_alter_table('queue_items', schema=None) as batch_op:
            batch_op.add_column(sa.Column('debug', sa.Boolean(), server_default=sa.text('0'), nullable=True))

    with op.batch_alter_table('poll_scheduler_config', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.create_index(op.f('ix_poll_scheduler_config_id'), ['id'], unique=False)

    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.alter_column('success_rate',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.drop_column('debug')
        batch_op.alter_column('success_rate',
                   existing_type=sa.Float(),
                   type_=sa.REAL(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('poll_scheduler_config', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_poll_scheduler_config_id'))
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   autoincrement=True)
    # ### end Alembic commands ###
